apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  annotations:
    deployment.kubernetes.io/revision: "2"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
      slowStart:
        delaySeconds: 5
        maxUnavailable: 25%
        maxSurge: 25%
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.11.13-alpine
